### ISSUE TITLE
Question about Arvelie and Neralie

### ISSUE THREAD

**Issue by croqaz** [XXIIVV/Oscean#28]
I'm fascinated and intrigued by arvelie and neralie, because they force you to look at time in a different way and I love that ... But I don't understand why these libraries exist for the creator of these libraries?

Are they purely artistic experiments?
Do they try to solve a problem that the current year-month-day calendar has?

In case of Arvelie I can see the date in format 2002-01-26 or maybe 20020126 can be compressed to 02B12 so that's handy.
But why "26 months of 14 days"? Is that time interval arbitrary?

Maybe writing just a bit more on the wiki.xxiivv.com page might also help other curious people like me :)

Thank you for making them open source 👍 !

**Comment by neauoire** [comment]
Hey @croqaz,

I will add to the wiki, some notes on reasoning behind the choice soon.

I find decimal time(neralie) highly efficient, especially for pomodoros. It's a tiny bit more precise but it makes a big difference.

The choice for the 14 days months, is because it aligns with the length of my sprints, I tend to "close a project or large task" within 2 weeks, I found 14 days to be a good span of time for a "monthly review". I just like that these 2 systems are a tiny bit more granular than seconds and 30 days months.

**Comment by croqaz** [comment]
Thank you for your quick answer. Sounds nice!
